// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU01Knz96HOtTrxRg5_On1PX80ph05lsE',
    appId: '1:601154102015:web:dfacbff47511ced7ade2ca',
    messagingSenderId: '601154102015',
    projectId: 'green-go-ba24b',
    authDomain: 'green-go-ba24b.firebaseapp.com',
    storageBucket: 'green-go-ba24b.appspot.com',
    measurementId: 'G-8PT28624VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFMQ4MFb8_IILl5PCj8Aitbx6-U_UMREg',
    appId: '1:601154102015:android:bc07eeb525e51ca9ade2ca',
    messagingSenderId: '601154102015',
    projectId: 'green-go-ba24b',
    storageBucket: 'green-go-ba24b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc8tDMjVHjF8qruOpatUMSU3n6EbRzFm0',
    appId: '1:601154102015:ios:40e8b4c79ea9fab8ade2ca',
    messagingSenderId: '601154102015',
    projectId: 'green-go-ba24b',
    storageBucket: 'green-go-ba24b.appspot.com',
    iosBundleId: 'com.example.greenGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc8tDMjVHjF8qruOpatUMSU3n6EbRzFm0',
    appId: '1:601154102015:ios:b4c9d572f0ed39c8ade2ca',
    messagingSenderId: '601154102015',
    projectId: 'green-go-ba24b',
    storageBucket: 'green-go-ba24b.appspot.com',
    iosBundleId: 'com.example.greenGo.RunnerTests',
  );
}
